language: node_js
node_js:
 - "4"
 - "6"
 - "8"
 - "node"
script:
  - npm run lint
  - npm test
  - npm run docs
after_success:
  - npm run coveralls
  - ./.travis_publish_docs
cache:
  directories:
    - node_modules
