language: node_js
node_js:
  - 10
  - 12
  - 14
  - lts/*
  - node
env:
  - DEFAULT_NODE_VERSION=14

branches:
  except:
    - gh-pages

script:
  # Test code
  - npm run lint
  - npm run build
  - npm run test:microtask
  - if [ "$TRAVIS_NODE_VERSION" != "10" ]; then
      npm run test:immediate;
    fi
  # Test documentation
  - npm run docs
  # Test packaging
  - npm pack
  - tar -xzf asynciterator-*.tgz
  - pushd package
  - node -e 'require(".")'
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      echo 'import { AsyncIterator } from "asynciterator"' > test.mjs;
      node test.mjs;
    fi
  - popd
  - npx tsc package/asynciterator.d.ts

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npx c8 report --reporter=text-lcov | npx coveralls;
      ./.travis_publish_docs;
    fi
