language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "node"
env:
  - DEFAULT_NODE_VERSION=14

script:
  # Test code
  - npm run lint
  - npm test
  # Test documentation
  - npm run docs
  # Test packaging
  - npm pack
  - tar -xzf asynciterator-*.tgz
  - cd package
  - node -e 'require(".")'
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      echo 'import { AsyncIterator } from "asynciterator"' > test.mjs;
      node test.mjs;
    fi

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/nyc --reporter=text-lcov -- node_modules/.bin/mocha |
        node_modules/.bin/coveralls;
      ./.travis_publish_docs;
    fi
