language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "node"
env:
  - DEFAULT_NODE_VERSION=12

script:
  - npm run lint
  - npm test
  - npm run docs

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/nyc --reporter=text-lcov -- node_modules/.bin/mocha |
        node_modules/.bin/coveralls;
      ./.travis_publish_docs;
    fi
