language: node_js
node_js:
  - 10
  - 12
  - 14
  - lts/*
  - node
env:
  - DEFAULT_NODE_VERSION=10

script:
  # Test code
  - npm run lint
  - npm test
  # Test documentation
  - npm run docs
  # Test packaging
  - npm pack
  - tar -xzf asynciterator-*.tgz
  - pushd package
  - node -e 'require(".")'
  - if [ "$TRAVIS_NODE_VERSION" == "14" ]; then
      echo 'import { AsyncIterator } from "asynciterator"' > test.mjs;
      node test.mjs;
    fi
  - popd

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm run cover;
      npx nyc report --reporter=text-lcov | npx coveralls;
      ./.travis_publish_docs;
    fi
