name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run test:microtask
      - run: npm run test:immediate
        if: ${{ matrix.node-version != '10.x' }}
      - run: npm pack
      - run: tar -xzf asynciterator-*.tgz
      - name: Test package
        if: ${{ matrix.node-version == '16.x' }}
        run: |
          pushd package
          node -e 'require(".")'
          echo 'import { AsyncIterator } from "asynciterator"' > test.mjs;
          node test.mjs;
          popd
      - run: npx tsc package/dist/asynciterator.d.ts
      - run: npx c8 --reporter=lcov mocha
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Consolidate test coverage from different jobs
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci --ignore-scripts
      - run: npm run docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            index.html
            docs
          retention-days: 1

  gh-pages:
    needs:
      - docs
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
